// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200708151216_v30-DailyChecks4")]
    partial class v30DailyChecks4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 775, DateTimeKind.Local).AddTicks(3946));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CountyId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Address","dbo");
                });

            modelBuilder.Entity("Data.Domain.AddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 774, DateTimeKind.Local).AddTicks(3616));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AddressType","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultName = "Home Address",
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Ev Adresi"
                        },
                        new
                        {
                            Id = 2,
                            DefaultName = "Work Address",
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "İş Adresi"
                        });
                });

            modelBuilder.Entity("Data.Domain.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentDoctorNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppointmentFinishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AppointmentRate")
                        .HasColumnType("int");

                    b.Property<string>("AppointmentRateNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId1")
                        .HasColumnType("int");

                    b.Property<string>("DoctorDeleteReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonationCompanys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 777, DateTimeKind.Local).AddTicks(2674));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("InProcess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("InProcessDates")
                        .HasColumnType("datetime2");

                    b.Property<int>("InProcessUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreview")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SessionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionPrice")
                        .HasColumnType("int");

                    b.Property<int>("SessionTime")
                        .HasColumnType("int");

                    b.Property<int>("SickId")
                        .HasColumnType("int");

                    b.Property<int?>("SickId1")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<string>("UserCancelReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("SickId");

                    b.HasIndex("SickId1");

                    b.HasIndex("UserId");

                    b.ToTable("Appointment","dbo");
                });

            modelBuilder.Entity("Data.Domain.AppointmentFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 781, DateTimeKind.Local).AddTicks(9645));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDoctor")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentFiles","dbo");
                });

            modelBuilder.Entity("Data.Domain.AppointmentProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 780, DateTimeKind.Local).AddTicks(8378));

                    b.Property<bool>("IsDoctor")
                        .HasColumnType("bit");

                    b.Property<string>("ProcessMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessTypes")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("AppointmentProcess","dbo");
                });

            modelBuilder.Entity("Data.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 768, DateTimeKind.Local).AddTicks(6700));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City","dbo");
                });

            modelBuilder.Entity("Data.Domain.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Data.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 767, DateTimeKind.Local).AddTicks(7047));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Country","dbo");
                });

            modelBuilder.Entity("Data.Domain.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 773, DateTimeKind.Local).AddTicks(2645));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("County","dbo");
                });

            modelBuilder.Entity("Data.Domain.DailyCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlertDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlertDayCounter")
                        .HasColumnType("int");

                    b.Property<string>("AlertDayHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Finish")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("NurseAlertDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NurseAlertDaysHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NurseId")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyCheck","dbo");
                });

            modelBuilder.Entity("Data.Domain.DailyCheckDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DailyCheckId")
                        .HasColumnType("int");

                    b.Property<int>("TitleOrder")
                        .HasColumnType("int");

                    b.Property<int>("ValuesTitleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyCheckId");

                    b.HasIndex("ValuesTitleId");

                    b.ToTable("DailyCheckDetail","dbo");
                });

            modelBuilder.Entity("Data.Domain.DailyCheckDetailValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DailyCheckDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TitleOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DailyCheckDetailId");

                    b.ToTable("DailyCheckDetailValues","dbo");
                });

            modelBuilder.Entity("Data.Domain.DailyCheckPackages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyCheckPackages","dbo");
                });

            modelBuilder.Entity("Data.Domain.DailyCheckPackagesValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("MaxValue")
                        .HasColumnType("real");

                    b.Property<float>("MinValue")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DailyCheckPackagesValues","dbo");
                });

            modelBuilder.Entity("Data.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 789, DateTimeKind.Local).AddTicks(1104));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Department","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-protection",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Alerji ve İmmünoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 2,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-neurosurgery",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beyin ve Sinir Cerrahisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 3,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-surgery-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cerrahi Onkoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 4,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-baby",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Cerrahisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 5,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-digestive-system",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Gastroenterolojisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 6,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-blood-sample",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Hematolojisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 7,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-care",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Kardiyolojisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 8,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-babies",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Psiyikatri",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 9,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-x-ray",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Romatolojisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 10,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-baby-boy",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Sağlığı ve Hastalıkları",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 11,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-kidneys-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Ürolojisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 12,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-dermatology",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Dermatoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 13,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-adrenal-gland",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Endokrinoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 14,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-infected-lungs",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Enfeksiyon",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 15,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-physical",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fizik Tedavi ve Rehabilitasyon",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 16,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-medical-tools",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Genel Cerrahi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 17,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-chest-pain",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Göğüs Cerrahisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 18,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-lung",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Göğüs Hastalıkları",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 19,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-eye",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Göz Hastalıkları",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 21,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-test",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hematoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 22,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-stomach",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "İç Hastalıkları",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 23,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-gynecology",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Jinekolojik Onkoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 24,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-sexual-health",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kadın Hastalıkları ve Doğum",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 25,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-heart-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kalp ve Damar Cerrahisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 26,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-cardiology",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kardiyoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 27,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-kulakburunbugaz",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kulak Burun Boğaz",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 28,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-kidney",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nefroloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 29,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-neurology-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Nöroloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 30,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-broken-arm",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Ortopedi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 31,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-surgery",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Plastik Cerrahi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 32,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-mental-health-2",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Psikiyatri",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 33,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-radiation",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Radyasyon Onkolojisi",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 34,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-joint-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Romatoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 35,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-quit-smoking-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sigarayı Bıraktırma",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 36,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-radiotherapy-1",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tıbbi Onkoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 37,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-uroloji",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Üroloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 38,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-burn",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Yanık Polikliniği",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 47,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-nutrition",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beslenme ve Diyet",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 48,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-newborn-2",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Doğum Koçu",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 49,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-breastfeeding",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Emzirme Danışmanı",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 50,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-listening",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Odyoloji",
                            ParentId = 0
                        },
                        new
                        {
                            Id = 51,
                            IDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IUser = 0,
                            Image = "flaticon-inspiration",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Psikoterapi ",
                            ParentId = 0
                        });
                });

            modelBuilder.Entity("Data.Domain.DoctorDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HospitalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 784, DateTimeKind.Local).AddTicks(5911));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PageView")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<string>("UniverstyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DoctorDetail","dbo");
                });

            modelBuilder.Entity("Data.Domain.DoctorEducations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDetailId");

                    b.ToTable("DoctorEducations","dbo");
                });

            modelBuilder.Entity("Data.Domain.DoctorExperiences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDetailId");

                    b.ToTable("DoctorExperiences","dbo");
                });

            modelBuilder.Entity("Data.Domain.DoctorMedicalInterests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDetailId");

                    b.ToTable("DoctorMedicalInterests");
                });

            modelBuilder.Entity("Data.Domain.DoctorScientificMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorDetailId");

                    b.ToTable("DoctorScientificMembership","dbo");
                });

            modelBuilder.Entity("Data.Domain.Donations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("DonationCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonationType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Data.Domain.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LogType")
                        .HasColumnType("int");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Data.Domain.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 766, DateTimeKind.Local).AddTicks(3114));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Menu","dbo");
                });

            modelBuilder.Entity("Data.Domain.MenuType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 765, DateTimeKind.Local).AddTicks(2766));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuType","dbo");
                });

            modelBuilder.Entity("Data.Domain.NotifyTokens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 790, DateTimeKind.Local).AddTicks(8991));

                    b.Property<DateTime?>("LastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("userType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotifyTokens","dbo");
                });

            modelBuilder.Entity("Data.Domain.NotifyWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NotifyWarning","dbo");
                });

            modelBuilder.Entity("Data.Domain.Referance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 764, DateTimeKind.Local).AddTicks(4690));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Referance","dbo");
                });

            modelBuilder.Entity("Data.Domain.RelUserDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 763, DateTimeKind.Local).AddTicks(1461));

                    b.Property<int>("IUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("SessionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("RelUserDepartment","dbo");
                });

            modelBuilder.Entity("Data.Domain.RoleGroup", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleGroup","dbo");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DefaultName = "Admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (short)3,
                            DefaultName = "User",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Data.Domain.Sick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 782, DateTimeKind.Local).AddTicks(7439));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sick","dbo");
                });

            modelBuilder.Entity("Data.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorDetailId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 750, DateTimeKind.Local).AddTicks(5580));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("defaultuser.png");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenEndTime")
                        .HasColumnType("datetime2");

                    b.Property<short>("RoleGroupId")
                        .HasColumnType("smallint");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<int>("UserDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleGroupId");

                    b.HasIndex("TypeId");

                    b.ToTable("User","dbo");
                });

            modelBuilder.Entity("Data.Domain.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bloodtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HearUs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime>("IDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 7, 8, 18, 12, 15, 783, DateTimeKind.Local).AddTicks(5803));

                    b.Property<int>("IUser")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegularlyMedicines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurgicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UUDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UUser")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDetail","dbo");
                });

            modelBuilder.Entity("Data.Domain.UserType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserType","dbo");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            DefaultName = "Doctor",
                            Name = "Doktor"
                        },
                        new
                        {
                            Id = (short)2,
                            DefaultName = "Nurse",
                            Name = "Hemşire"
                        },
                        new
                        {
                            Id = (short)3,
                            DefaultName = "Patient",
                            Name = "Hasta"
                        },
                        new
                        {
                            Id = (short)4,
                            DefaultName = "Admin",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Data.Domain.Address", b =>
                {
                    b.HasOne("Data.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Domain.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Domain.AddressType", "AddressType")
                        .WithMany("Address")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Domain.User", "User")
                        .WithMany("Address")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.Appointment", b =>
                {
                    b.HasOne("Data.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Domain.Department", null)
                        .WithMany("Appointment")
                        .HasForeignKey("DepartmentId1");

                    b.HasOne("Data.Domain.Sick", "Sick")
                        .WithMany()
                        .HasForeignKey("SickId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Domain.Sick", null)
                        .WithMany("Appointment")
                        .HasForeignKey("SickId1");

                    b.HasOne("Data.Domain.User", "User")
                        .WithMany("Appointment")
                        .HasForeignKey("UserId")
                        .HasConstraintName("UserAppointmen_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.AppointmentFiles", b =>
                {
                    b.HasOne("Data.Domain.Appointment", "Appointment")
                        .WithMany("AppointmentFiles")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.AppointmentProcess", b =>
                {
                    b.HasOne("Data.Domain.Appointment", "Appointment")
                        .WithMany("AppointmentProcess")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Data.Domain.City", b =>
                {
                    b.HasOne("Data.Domain.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.County", b =>
                {
                    b.HasOne("Data.Domain.City", "City")
                        .WithMany("Counties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DailyCheck", b =>
                {
                    b.HasOne("Data.Domain.User", "Nurse")
                        .WithMany("NurseDailyCheck")
                        .HasForeignKey("NurseId")
                        .HasConstraintName("nurseFrgn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Domain.User", "User")
                        .WithMany("DailyCheck")
                        .HasForeignKey("UserId")
                        .HasConstraintName("userFrgn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DailyCheckDetail", b =>
                {
                    b.HasOne("Data.Domain.DailyCheck", "DailyCheck")
                        .WithMany("DailyCheckDetail")
                        .HasForeignKey("DailyCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Domain.DailyCheckPackagesValues", "ValuesTitle")
                        .WithMany("DailyCheckDetail")
                        .HasForeignKey("ValuesTitleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DailyCheckDetailValues", b =>
                {
                    b.HasOne("Data.Domain.DailyCheckDetail", "DailyCheckDetail")
                        .WithMany("Values")
                        .HasForeignKey("DailyCheckDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DoctorDetail", b =>
                {
                    b.HasOne("Data.Domain.User", "User")
                        .WithOne("DoctorDetail")
                        .HasForeignKey("Data.Domain.DoctorDetail", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DoctorEducations", b =>
                {
                    b.HasOne("Data.Domain.DoctorDetail", "DoctorDetail")
                        .WithMany("DoctorEducations")
                        .HasForeignKey("DoctorDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DoctorExperiences", b =>
                {
                    b.HasOne("Data.Domain.DoctorDetail", "DoctorDetail")
                        .WithMany("DoctorExperiences")
                        .HasForeignKey("DoctorDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DoctorMedicalInterests", b =>
                {
                    b.HasOne("Data.Domain.DoctorDetail", "DoctorDetail")
                        .WithMany("DoctorMedicalInterests")
                        .HasForeignKey("DoctorDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.DoctorScientificMembership", b =>
                {
                    b.HasOne("Data.Domain.DoctorDetail", "DoctorDetail")
                        .WithMany("DoctorScientificMembership")
                        .HasForeignKey("DoctorDetailId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.Menu", b =>
                {
                    b.HasOne("Data.Domain.MenuType", "MenuType")
                        .WithMany("Menus")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.RelUserDepartment", b =>
                {
                    b.HasOne("Data.Domain.Department", "Department")
                        .WithMany("RelUserDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Domain.User", "User")
                        .WithMany("RelUserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.User", b =>
                {
                    b.HasOne("Data.Domain.RoleGroup", "RoleGroup")
                        .WithMany("Users")
                        .HasForeignKey("RoleGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Data.Domain.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Domain.UserDetail", b =>
                {
                    b.HasOne("Data.Domain.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("Data.Domain.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
